version: '3.8'

services:
  web:
    image: ghcr.io/git-adrianrubico/blog.adrianrubico.com:latest
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    command: python manage.py runserver
